//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rela_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesProcesed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImagesProcesed()
        {
            this.GoogleFaces = new HashSet<GoogleFace>();
            this.GoogleLabels = new HashSet<GoogleLabel>();
            this.GoogleLandmarks = new HashSet<GoogleLandmark>();
            this.GoogleLogoes = new HashSet<GoogleLogo>();
            this.MicrosoftFaces = new HashSet<MicrosoftFace>();
            this.Voices = new HashSet<Voice>();
            this.SimilarityTests = new HashSet<SimilarityTest>();
        }
    
        public int imageId { get; set; }
        public System.DateTime date { get; set; }
        public string UserId { get; set; }
        public string image { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoogleFace> GoogleFaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoogleLabel> GoogleLabels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoogleLandmark> GoogleLandmarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoogleLogo> GoogleLogoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MicrosoftFace> MicrosoftFaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voice> Voices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimilarityTest> SimilarityTests { get; set; }
    }
}
