//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rela_project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RelaEntities : DbContext
    {
        public RelaEntities()
            : base("name=RelaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GoogleFace> GoogleFaces { get; set; }
        public virtual DbSet<GoogleLabel> GoogleLabels { get; set; }
        public virtual DbSet<GoogleLandmark> GoogleLandmarks { get; set; }
        public virtual DbSet<GoogleLogo> GoogleLogoes { get; set; }
        public virtual DbSet<MicrosoftFace> MicrosoftFaces { get; set; }
        public virtual DbSet<Voice> Voices { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ImagesProcesed> ImagesProceseds { get; set; }
        public virtual DbSet<SimilarityTest> SimilarityTests { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
    }
}
