//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rela_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimilarityTest
    {
        public int similarityId { get; set; }
        public string father { get; set; }
        public string mother { get; set; }
        public Nullable<int> imageId { get; set; }
    
        public virtual ImagesProcesed ImagesProcesed { get; set; }
    }
}
