//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelaService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long id { get; set; }
        public string hostname { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> time_accessed { get; set; }
        public string url { get; set; }
        public Nullable<bool> success { get; set; }
        public Nullable<decimal> score { get; set; }
        public string action { get; set; }
        public string challenge_ts { get; set; }
    }
}
